version: '3.3'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '3000:3000'
    environment:
      - DATABASE_URL=postgres://blog_user:123456@db:5432/blog
      - JWT_SECRET=secret
    depends_on:
      - db
    networks:
      - blog-network

  db:
    image: postgres:15
    environment:
      - POSTGRES_USER=blog_user
      - POSTGRES_PASSWORD=123456
      - POSTGRES_DB=blog
    ports:
      - '5433:5432'
    volumes:
      - db_data:/var/lib/postgresql/data
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U blog_user -d blog']
      interval: 5s
      timeout: 5s
      retries: 5
    networks:
      - blog-network

networks:
  blog-network:
    driver: bridge

volumes:
  db_data:
